#!/usr/bin/env bash
# Pull Vercel env vars into namespaced files: .env.vercel.<project_slug>
# Prerequisites: Vercel CLI (see package.json / docs/VERCEL_ENV_SYNC.md) and `vercel login`.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if ! command -v vercel >/dev/null 2>&1; then
  echo "Vercel CLI not found. Install it globally, or use: npx vercel@latest <command>"
  echo "Example: npm i -g vercel   # https://vercel.com/docs/cli"
  exit 1
fi

PROJECTS=(
  "cursor-hackathon-london-2026-1"
  "cursor-hackathon-london-2026-0"
  "cursor-hack-london-2026-1"
  "cursor-thrads-london-2026"
)

ENVIRONMENT="${VERCEL_ENV:-production}"

echo "Using Vercel environment: ${ENVIRONMENT} (override with VERCEL_ENV=development|preview|production)"
echo ""

for slug in "${PROJECTS[@]}"; do
  out="$ROOT/.env.vercel.$slug"
  echo "→ Link + env pull for project: $slug → $(basename "$out")"
  vercel link --yes --project "$slug"
  vercel env pull "$out" --environment="$ENVIRONMENT" --yes
  echo ""
done

# Merge helper (optional): append into a combined file for diffing (does not overwrite .env.local)
COMBINED="$ROOT/.env.vercel.all.merged"
{
  echo "# Generated by scripts/sync-vercel-envs.sh — per-project pulls stored separately as .env.vercel.*"
  echo "# Merged view (duplicates last-wins per key order below)."
  echo ""
  for slug in "${PROJECTS[@]}"; do
    f="$ROOT/.env.vercel.$slug"
    if [[ -f "$f" ]]; then
      echo "## --- $slug ---"
      cat "$f"
      echo ""
    fi
  done
} > "$COMBINED"

echo "Wrote merged snapshot: $COMBINED (review for conflicts; keep secrets out of git)"
