#!/usr/bin/env bash
# Pull Vercel env vars into namespaced files: .env.vercel.<project_slug>
# Non-interactive: uses global --non-interactive (avoid legacy/subcommand --yes quirks).
# Resolves CLI as: global `vercel` if on PATH, else `npx vercel@latest`.
# Prerequisites: `vercel login` or `npx vercel@latest login`.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if command -v vercel >/dev/null 2>&1; then
  VERCEL=(vercel)
else
  echo "No global \`vercel\` on PATH — using npx vercel@latest"
  VERCEL=(npx vercel@latest)
fi

PROJECTS=(
  "cursor-hackathon-london-2026-1"
  "cursor-hackathon-london-2026-0"
  "cursor-hack-london-2026-1"
  "cursor-thrads-london-2026"
)

ENVIRONMENT="${VERCEL_ENV:-production}"

echo "Using Vercel environment: ${ENVIRONMENT} (override with VERCEL_ENV=development|preview|production)"
echo ""

for slug in "${PROJECTS[@]}"; do
  out="$ROOT/.env.vercel.$slug"
  echo "→ Link + env pull for project: $slug → $(basename "$out")"
  "${VERCEL[@]}" --non-interactive link --project "$slug"
  "${VERCEL[@]}" env pull "$out" --environment="$ENVIRONMENT" --non-interactive
  echo ""
done

# Merge helper (optional): append into a combined file for diffing (does not overwrite .env.local)
COMBINED="$ROOT/.env.vercel.all.merged"
{
  echo "# Generated by scripts/sync-vercel-envs.sh — per-project pulls stored separately as .env.vercel.*"
  echo "# Merged view (duplicates last-wins per key order below)."
  echo ""
  for slug in "${PROJECTS[@]}"; do
    f="$ROOT/.env.vercel.$slug"
    if [[ -f "$f" ]]; then
      echo "## --- $slug ---"
      cat "$f"
      echo ""
    fi
  done
} > "$COMBINED"

echo "Wrote merged snapshot: $COMBINED (review for conflicts; keep secrets out of git)"
